Fixes Proxy getter issue
When the object $value is an array and the script tries to access
to an exixting index, the getter returns the interger instead of
the proxy with the actions.

E.g.

TypeError: Object 1043 has no method '$get'
    at <error: illegal access>
    at OVHWS.proxyResponseREST (ovh.js:256:16)
    at IncomingMessage.<anonymous> (ovh.js:356:19)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:895:16
    at process._tickCallback (node.js:415:13)